name: get_base_code
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: ^5.6.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  logger: ^2.2.0
  dropdown_button2: ^1.9.2
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1

  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/map.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/map.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/map.png"
    icon_size: 48 # min:48, max:256, default: 48

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

  

